# https://github.com/realm/SwiftLint#configuration

line_length: 150

disabled_rules:
  - identifier_name
  - trailing_comma
  - force_cast
  - nesting
  - multiple_closures_with_trailing_closure

excluded:
  - Carthage
  - Pods
