# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: GitHub
options:
  bundleIdPrefix: com.rono23
  indentWidth: 2
  tabWidth: 2
targets:
  GitHub:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    sources: [GitHub]
    postCompileScripts:
      - name: SwiftFormat
        script: swiftformat .
      - name: SwiftLint
        script: swiftlint
    dependencies:
      - carthage: OAuthSwift
      - carthage: KeychainAccess
    settings:
      TARGETED_DEVICE_FAMILY: 1
